config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/octocat/Hello-World:
      branch: master
      repo: https://github.com/octocat/Hello-World
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/octocat/Hello-World git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-beige-owl.sh
        container: qc.acc_paltry-puce-antelope
  QC.Doc:
    repos:
      github.com/octocat/Hello-World find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lilac-ostrich.sh
        container: qc.doc_dorky-cream-wolverine
      github.com/octocat/Hello-World git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-goldenrod-horse.sh
        container: qc.doc_frumpy-dandelion-eagle
  QC.Lic:
    repos:
      github.com/octocat/Hello-World licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-asparagus-discus.sh
        container: qc.lic_goopy-lavender-lemur
  QC.Ver:
    repos:
      github.com/octocat/Hello-World get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cerise-dhole.sh
        container: qc.ver_snazzy-red-buzzard
timeout: 5400
