config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/octocat/Hello-World:
      branch: master
      repo: https://github.com/octocat/Hello-World
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/octocat/Hello-World git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-ultramarine-horse.sh
        container: qc.acc_whiny-celadon-wasp
  QC.Doc:
    repos:
      github.com/octocat/Hello-World find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-orchid-sparrow.sh
        container: qc.doc_bluesy-heliotrope-chinchilla
      github.com/octocat/Hello-World git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-peach-caiman.sh
        container: qc.doc_sickly-seashell-giraffe
  QC.Lic:
    repos:
      github.com/octocat/Hello-World licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-teal-kangaroo.sh
        container: qc.lic_pasty-cerise-jackal
  QC.Ver:
    repos:
      github.com/octocat/Hello-World get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-grey-swan.sh
        container: qc.ver_nippy-beige-coral
timeout: 5400
