config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/octocat/Hello-World:
      branch: master
      repo: https://github.com/octocat/Hello-World
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/octocat/Hello-World git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-jade-woodlouse.sh
        container: qc.acc_fuzzy-green-olm
  QC.Doc:
    repos:
      github.com/octocat/Hello-World find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-carmine-zorse.sh
        container: qc.doc_chummy-grey-fish
      github.com/octocat/Hello-World git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-blue-foxhound.sh
        container: qc.doc_bumpy-pumpkin-zebra
  QC.Lic:
    repos:
      github.com/octocat/Hello-World licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-denim-wildebeest.sh
        container: qc.lic_lovely-azure-dachsbracke
  QC.Ver:
    repos:
      github.com/octocat/Hello-World get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-coral-squid.sh
        container: qc.ver_homely-sangria-butterfly
timeout: 5400
